"""add first_name and last_name to users

Revision ID: 59275c41c5a9
Revises: 611b9bc9115d
Create Date: 2026-09-02 07:00:48.277033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59275c41c5a9'
down_revision: Union[str, Sequence[str], None] = '611b9bc9115d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('first_name', sa.String(length=100), nullable=False, server_default=''),
    )
    op.add_column(
        'users',
        sa.Column('last_name', sa.String(length=100), nullable=False, server_default=''),
    )
    op.alter_column('users', 'first_name', server_default=None)
    op.alter_column('users', 'last_name', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
